export { default as PaperTexture } from './texture-paper.webp'
export { default as Myself } from './myself.webp'
export { default as LandingFLThumb } from './landing-fl-thumbnail.webp'
export { default as TastynasThumb } from './tastynas.webp'
export { default as PDAMTCThumb } from './pdamtc-thumbnail.webp'
export { default as GISThumb } from './gis-thumbnail.webp'
export { default as LinkedinBG } from './linkedin-bg.webp'
export { default as EmailBG } from './email-bg.webp'
export { default as Noise } from './noise.webp'

export { default as ReactLogo } from './logo/React.webp'
export { default as NextLogo } from './logo/nextjs.webp'
export { default as TailwindLogo } from './logo/tailwind.webp'
export { default as ExpressLogo } from './logo/express.webp'
export { default as FeedloopLogo } from './logo/feedloop.webp'